document.addEventListener('DOMContentLoaded', async () => {
  const targetSelect = document.getElementById('ll-target-lang');
  const nativeSelect = document.getElementById('ll-native-lang');
  const activateBtn = document.getElementById('ll-activate');
  const statusDot = document.getElementById('ll-status-dot');
  const statusText = document.getElementById('ll-status-text');
  const apiKeyInput = document.getElementById('ll-api-key');
  const apiSaveBtn = document.getElementById('ll-api-save');
  const apiStatus = document.getElementById('ll-api-status');
  const toggleBtn = document.getElementById('ll-toggle-subs');
  const vocabBtn = document.getElementById('ll-open-vocab');

  // Check API key status
  chrome.runtime.sendMessage({ type: 'CHECK_API_KEY' }, res => {
    if (res?.hasKey) {
      apiStatus.textContent = '✓ Configurada';
      apiStatus.style.color = '#34d399';
    } else {
      apiStatus.textContent = 'No configurada — los subtítulos duales funcionan sin ella';
      apiStatus.style.color = '#64748b';
    }
  });

  apiSaveBtn.addEventListener('click', () => {
    const key = apiKeyInput.value.trim();
    if (!key) return;
    chrome.runtime.sendMessage({ type: 'SAVE_API_KEY', key }, res => {
      if (res?.success) {
        apiKeyInput.value = '';
        apiStatus.textContent = '✓ Guardada';
        apiStatus.style.color = '#34d399';
      }
    });
  });

  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  if (!tab?.url?.includes('youtube.com/watch')) {
    statusText.textContent = 'Abre un video de YouTube para empezar';
    return;
  }

  try {
    const res = await chrome.tabs.sendMessage(tab.id, { type: 'GET_STATE' });
    if (res?.tracks?.length) {
      statusDot.className = 'll-status-dot ll-status-active';
      statusText.textContent = `${res.tracks.length} idiomas disponibles`;
      res.tracks.forEach(t => {
        const opt = document.createElement('option');
        opt.value = t.languageCode;
        opt.textContent = `${t.languageName}${t.isAutoGenerated ? ' (auto)' : ''}`;
        targetSelect.appendChild(opt);
      });
      if (res.config?.targetLang) targetSelect.value = res.config.targetLang;
      if (res.config?.nativeLang) nativeSelect.value = res.config.nativeLang;
      if (res.ready) {
        activateBtn.textContent = '✓ Subtítulos activos';
        activateBtn.style.background = 'linear-gradient(135deg, #059669, #34d399)';
      }
    } else {
      statusDot.className = 'll-status-dot ll-status-loading';
      statusText.textContent = 'Cargando subtítulos...';
    }
  } catch {
    statusText.textContent = 'Recarga la página de YouTube';
  }

  function checkReady() { activateBtn.disabled = !(targetSelect.value && nativeSelect.value); }
  targetSelect.addEventListener('change', checkReady);
  nativeSelect.addEventListener('change', checkReady);
  checkReady();

  activateBtn.addEventListener('click', async () => {
    const tl = targetSelect.value, nl = nativeSelect.value;
    if (!tl || !nl) return;
    activateBtn.textContent = 'Activando...'; activateBtn.disabled = true;
    chrome.storage.sync.set({ targetLang: tl, nativeLang: nl });
    try {
      const r = await chrome.tabs.sendMessage(tab.id, { type: 'ACTIVATE_DUAL', targetLang: tl, nativeLang: nl });
      if (r?.success) {
        activateBtn.textContent = '✓ Subtítulos activos';
        activateBtn.style.background = 'linear-gradient(135deg, #059669, #34d399)';
        visible = true;
        updateToggleBtn();
      }
    } catch { activateBtn.textContent = 'Error — reintentar'; activateBtn.disabled = false; }
  });

  // Toggle subtitles with visual state
  let visible = true;
  function updateToggleBtn() {
    if (visible) {
      toggleBtn.textContent = '👁 Visibles';
      toggleBtn.classList.add('ll-action-active');
      toggleBtn.classList.remove('ll-action-inactive');
    } else {
      toggleBtn.textContent = '👁‍🗨 Ocultos';
      toggleBtn.classList.remove('ll-action-active');
      toggleBtn.classList.add('ll-action-inactive');
    }
  }
  updateToggleBtn();

  toggleBtn.addEventListener('click', async () => {
    visible = !visible;
    updateToggleBtn();
    await chrome.tabs.sendMessage(tab.id, { type: 'TOGGLE_SUBS', visible });
  });

  // Vocab button with word count
  vocabBtn.addEventListener('click', () => {
    chrome.sidePanel.open({ windowId: tab.windowId });
  });

  chrome.runtime.sendMessage({ type: 'GET_VOCABULARY' }, res => {
    const count = res?.vocabulary?.length || 0;
    vocabBtn.textContent = count > 0 ? `📚 Vocab (${count})` : '📚 Vocab';
  });
});
