/**
 * page-script.js — MAIN world
 * Uses captured pot token to fetch caption tracks directly,
 * replicating Language Reactor's approach.
 */
(function () {
  'use strict';
  const PREFIX = 'LINGUA_LENS';

  function waitForPlayer(max = 50) {
    return new Promise((resolve, reject) => {
      let n = 0;
      const iv = setInterval(() => {
        const p = document.querySelector('#movie_player');
        if (p && typeof p.getOption === 'function') { clearInterval(iv); resolve(p); }
        if (++n >= max) { clearInterval(iv); reject(new Error('Player not found')); }
      }, 300);
    });
  }

  function getAvailableTracks(player) {
    try {
      const tracklist = player.getOption('captions', 'tracklist') || [];
      return tracklist.map(t => ({
        languageCode: t.languageCode,
        languageName: t.displayName || t.languageName || t.languageCode,
        kind: t.kind || 'standard',
        isAutoGenerated: t.kind === 'asr',
      }));
    } catch (e) { return []; }
  }

  function getVideoId() {
    return new URLSearchParams(location.search).get('v');
  }

  // Wait for pot token (YouTube loads captions on page load, triggering our XHR interceptor)
  async function waitForPot(videoId, maxWaitMs = 5000) {
    const start = Date.now();
    while (Date.now() - start < maxWaitMs) {
      if (window.__llPotStore[videoId]) return window.__llPotStore[videoId];
      await new Promise(r => setTimeout(r, 200));
    }
    console.warn('[LL] pot token not captured in time');
    return null;
  }

  function getCaptionBaseUrl(player, lang) {
    try {
      const caps = player.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (!caps) return null;
      // Prefer non-ASR track for the requested language
      const track = caps.find(t => t.languageCode === lang && t.kind !== 'asr')
                 || caps.find(t => t.languageCode === lang);
      return track?.baseUrl || null;
    } catch (e) { return null; }
  }

  async function fetchCaptions(baseUrl, pot, fmt, tlang) {
    let url = baseUrl + '&fmt=' + fmt;
    if (tlang) url += '&tlang=' + tlang;
    if (pot) {
      url += '&c=WEB';
      url += '&pot=' + pot;
    }

    try {
      const res = await fetch(url);
      if (!res.ok) return [];
      const text = await res.text();
      if (!text || text.length === 0) return [];
      const data = JSON.parse(text);
      if (!data.events) return [];
      return data.events.filter(e => e.segs?.length).map(e => ({
        startMs: e.tStartMs,
        durationMs: e.dDurationMs,
        endMs: e.tStartMs + (e.dDurationMs || 0),
        text: e.segs.map(s => s.utf8).join('').replace(/\n/g, ' '),
      }));
    } catch (e) {
      console.error('[LL] fetchCaptions error:', e);
      return [];
    }
  }

  async function init() {
    try {
      const player = await waitForPlayer();
      const tracks = getAvailableTracks(player);
      window.postMessage({ type: `${PREFIX}_TRACKS_AVAILABLE`, tracks }, '*');

      window.addEventListener('message', async (ev) => {
        if (ev.source !== window || ev.data?.type !== `${PREFIX}_ACTIVATE`) return;

        const { targetLang, nativeLang } = ev.data;
        const videoId = getVideoId();
        console.log(`[LL] Activating: ${targetLang} + ${nativeLang} for ${videoId}`);

        // Ensure YouTube has loaded captions (triggers XHR with pot)
        player.setOption('captions', 'track', { languageCode: targetLang });

        // Wait for pot token from XHR interceptor
        const pot = await waitForPot(videoId);
        console.log(`[LL] pot: ${pot ? pot.substring(0, 30) + '...' : 'NOT FOUND'}`);

        // Get base URL for the target language track
        const baseUrl = getCaptionBaseUrl(player, targetLang);
        if (!baseUrl) {
          console.error('[LL] No baseUrl found for', targetLang);
          return;
        }

        // Check if native language has its own track
        const nativeBaseUrl = getCaptionBaseUrl(player, nativeLang);

        // Fetch target captions
        console.log('[LL] Fetching target captions...');
        const targetCaptions = await fetchCaptions(baseUrl, pot, 'json3');

        // Fetch native captions — either from its own track or via tlang translation
        console.log('[LL] Fetching native captions...');
        let nativeCaptions;
        if (nativeBaseUrl) {
          // Native language has its own track — fetch directly
          nativeCaptions = await fetchCaptions(nativeBaseUrl, pot, 'json3');
        }
        if (!nativeCaptions || nativeCaptions.length === 0) {
          // Fall back to auto-translate via tlang
          nativeCaptions = await fetchCaptions(baseUrl, pot, 'json3', nativeLang);
        }

        console.log(`[LL] Loaded: ${targetCaptions.length} target + ${nativeCaptions.length} native`);

        window.postMessage({
          type: `${PREFIX}_ALL_CAPTIONS`,
          targetLang, nativeLang,
          target: targetCaptions,
          native: nativeCaptions,
        }, '*');
      });
    } catch (e) { console.error('[LL] init:', e); }
  }

  // SPA navigation
  let lastUrl = location.href;
  new MutationObserver(() => {
    if (location.href !== lastUrl) {
      lastUrl = location.href;
      if (location.pathname === '/watch') setTimeout(init, 1500);
    }
  }).observe(document.body, { childList: true, subtree: true });

  if (location.pathname === '/watch') init();
})();
