/**
 * page-script.js — MAIN world
 * Lee captions del DOM de YouTube via MutationObserver.
 * Comunica vía postMessage → caption-interceptor.js (ISOLATED world).
 */
(function () {
  'use strict';
  const PREFIX = 'LINGUA_LENS';

  function waitForPlayer(max = 50) {
    return new Promise((resolve, reject) => {
      let n = 0;
      const iv = setInterval(() => {
        const p = document.querySelector('#movie_player');
        if (p && typeof p.getOption === 'function') { clearInterval(iv); resolve(p); }
        if (++n >= max) { clearInterval(iv); reject(new Error('Player not found')); }
      }, 300);
    });
  }

  function getAvailableTracks(player) {
    try {
      const tracklist = player.getOption('captions', 'tracklist') || [];
      return tracklist.map(t => ({
        languageCode: t.languageCode,
        languageName: t.displayName || t.languageName || t.languageCode,
        kind: t.kind || 'standard',
        isAutoGenerated: t.kind === 'asr',
      }));
    } catch (e) { console.error('[LL] getAvailableTracks:', e); return []; }
  }

  let captionObserver = null;
  let lastText = '';

  function waitForCaptionContainer(max = 30) {
    return new Promise((resolve) => {
      let n = 0;
      const iv = setInterval(() => {
        const c = document.querySelector('.ytp-caption-window-container');
        if (c) { clearInterval(iv); resolve(c); }
        if (++n >= max) { clearInterval(iv); resolve(null); }
      }, 200);
    });
  }

  async function startCaptionObserver(player) {
    stopCaptionObserver();

    const container = await waitForCaptionContainer();
    if (!container) {
      console.warn('[LL] No caption container found');
      return;
    }

    captionObserver = new MutationObserver(() => {
      const segments = container.querySelectorAll('.ytp-caption-segment');
      if (!segments.length) {
        if (lastText !== '') {
          lastText = '';
          window.postMessage({ type: `${PREFIX}_CAPTION_UPDATE`, text: '', time: player.getCurrentTime() }, '*');
        }
        return;
      }

      const text = [...segments].map(s => s.textContent).join(' ').trim();
      // Filter out YouTube UI text that leaks into captions
      const cleaned = text.replace(/^(.*?Click\s+for\s+settings\s*)/i, '').trim();

      if (cleaned && cleaned !== lastText) {
        lastText = cleaned;
        window.postMessage({
          type: `${PREFIX}_CAPTION_UPDATE`,
          text: cleaned,
          time: player.getCurrentTime(),
        }, '*');
      }
    });

    captionObserver.observe(container, { childList: true, subtree: true, characterData: true });
    console.log('[LL] Caption observer active on container');
  }

  function stopCaptionObserver() {
    if (captionObserver) {
      captionObserver.disconnect();
      captionObserver = null;
      lastText = '';
    }
  }

  async function init() {
    try {
      const player = await waitForPlayer();
      const tracks = getAvailableTracks(player);
      window.postMessage({ type: `${PREFIX}_TRACKS_AVAILABLE`, tracks }, '*');

      window.addEventListener('message', (ev) => {
        if (ev.source !== window) return;

        if (ev.data?.type === `${PREFIX}_SET_TRACK`) {
          try {
            player.setOption('captions', 'track', { languageCode: ev.data.lang });
            startCaptionObserver(player);
          } catch (e) { console.error('[LL] setOption:', e); }
        }

        if (ev.data?.type === `${PREFIX}_STOP_OBSERVER`) {
          stopCaptionObserver();
        }
      });
    } catch (e) { console.error('[LL] init:', e); }
  }

  // Re-init on YouTube SPA navigation
  let lastUrl = location.href;
  new MutationObserver(() => {
    if (location.href !== lastUrl) {
      lastUrl = location.href;
      stopCaptionObserver();
      if (location.pathname === '/watch') setTimeout(init, 1500);
    }
  }).observe(document.body, { childList: true, subtree: true });

  if (location.pathname === '/watch') init();
})();
